KOD-7.4 Zadanie: Obliczamy liczbę ludzi na świecie
piotr-kostka/piotr-kostka-kodilla-java pull request #14
Opened 2022-04-15 14:48 UTC by piotr-kostka

Czy idzie mi to w dobrym kierunku? Co mam dalej zrobić bo trochę się pogubiłem czy te kontynenty mają być tak zrobione?

2022-04-15 17:40 UTC, mps4dev requested changes
Nie mozesz miec klas szczegolowych np Africa, Asia … klasa Continent powinna miec wlasciwosci name i peopleQuantity

2022-04-15 21:30 UTC, piotr-kostka commented
Sprawdź proszę czy klasy Country, Continent i World tak mają wyglądać

2022-04-16 17:52 UTC, mps4dev requested changes
Generalnie jest ok

2022-04-16 17:52 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Continent.java
> +public final class Continent {
Trzymamy w kolekcji, dlatego nadpisujemy equals i hashCode

2022-04-16 17:52 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Continent.java
> +    private final List<Country> countries = new ArrayList<>();
Dobrze, by kontynent mial nazwe :)

2022-04-16 17:52 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Country.java
> +    private final String countryName;
wystarczy name, wiadomo ze country, bo jestesmy w klasie Counbry

2022-04-16 17:52 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Country.java
> +    private final BigDecimal quantityOfPeople;
peopleQuantity

2022-04-17 16:53 UTC, mps4dev requested changes

2022-04-17 16:53 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Continent.java
> +
Name wystarczy

2022-04-18 16:42 UTC, mps4dev approved these changes

2022-04-18 17:23 UTC, merged