KOD-13.4 Zadanie: wyzwanie - Food2Door
piotr-kostka/piotr-kostka-kodilla-java pull request #30
Opened 2022-05-27 17:01 UTC by piotr-kostka

2022-05-27 17:01 UTC, piotr-kostka commented
Czy o takie coś chodzi? Jak zróżnicować implementacje metody process() dla sklepów?

2022-05-27 17:53 UTC, mps4dev requested changes
Za duzo jest zaleznosci miedzy obiektami. Sklep mie musi dostawac informacji o sklepie.

2022-05-28 17:40 UTC, mps4dev requested changes

2022-05-28 17:40 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/Product.java
> +    private int ID;
Od kiedy uzywamy wielkich liter dla nazw pol?

2022-05-28 17:40 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/ExtraFoodShop.java
> +        System.out.println("Thank you for choosing ExtraFoodShop! Free delivery today!");
Wypisz jakies info zwiazane z tym kto zamawia, kiedy i co. Np. Zamowienie nr …. Dla ExtraFoodShop z dnia ….. dla ….: produkt …. Ilosc ….

2022-05-29 12:01 UTC, mps4dev approved these changes

2022-05-29 13:09 UTC, merged