KOD-13.5 Zadanie: wyzwanie - loty
piotr-kostka/piotr-kostka-kodilla-java pull request #34
Opened 2022-05-30 15:24 UTC by piotr-kostka

2022-05-30 16:41 UTC, mps4dev requested changes

2022-05-30 16:41 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/flights/FlightSearcher.java
> +    public void searchByDeparture(String departure) {
Metoda search ma cos wyszukac - pojedyncza odpowiedzialnosc. Nie ma nic wypisywac.

2022-05-30 16:41 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/flights/FlightSearcher.java
> +    public void searchConnectingFlight(String departure, String connectingAirport, String arrival) {
Masz znalezc loty z lotniska A na lotnisko B z przesiadka

2022-05-30 22:17 UTC, mps4dev requested changes

2022-05-30 22:17 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/flights/FlightSearcher.java
> +    public List<Flight> searchFlightWithInterchange(String departure, String arrival, String connectingAirport) {
Ta metoda ma miec dwa argumenty :( departure i arrival

2022-05-31 16:53 UTC, mps4dev requested changes

2022-06-01 05:42 UTC, piotr-kostka commented
Zmieniona metoda - udało mi się to zrobić za pomocą pętli; jak to zrobić za pomocą streama chciałbym obgadać na spotkaniu

2022-06-01 16:43 UTC, mps4dev approved these changes

2022-06-01 16:59 UTC, merged