KOD-6.6 rozbudowa BookLibrary
piotr-kostka/piotr-kostka-kodilla-java pull request #8
Opened 2022-04-11 21:12 UTC by piotr-kostka

Snippet testów - potrzebuję pomocy co zrobić żeby metoda listBooksInHandsOf(LibraryUser libraryUser) różniła się od metody z interfejsu - zablokowało mnie to na dobre

2022-04-12 14:57 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/library/Book.java
> +}
Uczymy sie dodawac tez metode toString()

2022-04-12 18:00 UTC, piotr-kostka commented
Co tu robię źle w tej implementacji?

2022-04-12 20:24 UTC, mps4dev requested changes

2022-04-12 20:24 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/library/BookLibrary.java
> +        List<Book> bookList = new ArrayList<>();
Po co tak kombiniwac? Napisalem jak ma byc :)
return libraryDatabase.listBooksInHandsOf(imuser);

2022-04-13 18:24 UTC, mps4dev approved these changes

2022-04-13 18:25 UTC, merged